Repository UnspokenTeam/Calendar, pull requests merged in 2024-05, with the labels that each got.

#71 feat: add multiple invite create in invite service
  .pre-commit-config.yaml
  invite_service/db/postgres_client.py
  invite_service/poetry.lock
  invite_service/pyproject.toml
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  invite_service/src/models/invite.py
  shared/proto/invite_service/invite_service.proto
Labels: enhancement

#74 Fix: errors in invite service
  invite_service/main.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
Labels: bug

#77 Feat: add invite route to gateway
  gateway/app/grpc_client/grpc_client.py
  gateway/app/main.py
  gateway/app/middleware/interceptor.py
  gateway/app/models/__init__.py
  gateway/app/models/invite.py
  gateway/app/routers/__init__.py
  gateway/app/routers/invites.py
  gateway/poetry.lock
  gateway/pyproject.toml
  pyproject.toml
  shared/proto/invite_service/invite_service.proto
Labels: enhancement

#76 fix: can't create event when pending event has been deleted in invite service
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/mock_invite_repository.py
Labels: bug

#60 Feat: Create new requests for event service
  .pre-commit-config.yaml
  event_service/db/postgres_client.py
  event_service/errors/wrong_interval_error.py
  event_service/main.py
  event_service/poetry.lock
  event_service/prisma/schema.prisma
  event_service/pyproject.toml
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/src/models/event.py
  event_service/utils/ai_client.py
  event_service/utils/custom_interceptor.py
  notification_service/db/postgres_client.py
  notification_service/main.py
  notification_service/poetry.lock
  notification_service/pyproject.toml
  notification_service/src/models/notification.py
  notification_service/src/notification_service_impl.py
  shared/proto/event_service/event_service.proto
  tox.ini
Labels: bug, enhancement

#73 Feat/add notification route to gateway
  gateway/app/grpc_client/grpc_client.py
  gateway/app/main.py
  gateway/app/models/__init__.py
  gateway/app/models/notification.py
  gateway/app/routers/__init__.py
  gateway/app/routers/notification.py
  gateway/app/validators/__init__.py
  gateway/app/validators/int_validators.py
  gateway/app/validators/str_validators.py
Labels: enhancement

#75 fix: typo in get_invites_by_invitee_id in invite service
  invite_service/repository/mock_invite_repository.py
Labels: bug

#80 Feat: add returns in create and update functions in identity service
  .gitignore
  gateway/app/middleware/auth.py
  gateway/app/models/user.py
  gateway/app/routers/invites.py
  gateway/app/routers/users.py
  identity_service/poetry.lock
  identity_service/pyproject.toml
  identity_service/repository/mock_user_repository.py
  identity_service/repository/user_repository_impl.py
  identity_service/repository/user_repository_interface.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
  shared/proto/identity_service/auth.proto
  shared/proto/identity_service/get_user.proto
  shared/proto/identity_service/identity_service.proto
  shared/proto/identity_service/update_user.proto
Labels: enhancement

#79 Fix: Add return objects for requests and correct return types in proto for notification service
  notification_service/main.py
  notification_service/prisma/schema.prisma
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
  notification_service/repository/notification_repository_interface.py
  notification_service/src/models/notification.py
  notification_service/src/notification_service_impl.py
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#78 Fix: Add return objects for requests and correct return types in proto for event service
  event_service/constants.py
  event_service/prisma/schema.prisma
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/src/models/event.py
  shared/proto/event_service/event_service.proto
Labels: enhancement

#84 Feat: Add search by time interval in get_events_by_events_ids
  event_service/constants.py
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  shared/proto/event_service/event_service.proto
Labels: enhancement

#82 fix: switch to UUID4 | str from UUID in gateway
  gateway/app/models/invite.py
  gateway/app/models/notification.py
  gateway/app/models/user.py
  gateway/app/routers/invites.py
  gateway/app/routers/notification.py
  gateway/app/routers/users.py
Labels: bug

#81 feat: add get_user_by_email to gateway
  gateway/app/main.py
  gateway/app/middleware/auth.py
  gateway/app/middleware/interceptor.py
  gateway/app/models/invite.py
  gateway/app/routers/invites.py
  gateway/app/routers/notification.py
  gateway/app/routers/users.py
Labels: enhancement

#88 Feat: add event routes to gateway
  .gitignore
  gateway/app/models/__init__.py
  gateway/app/models/event.py
  gateway/app/models/user.py
  gateway/app/routers/events.py
  gateway/app/routers/invites.py
  gateway/app/routers/notification.py
  gateway/app/routers/users.py
Labels: enhancement

#89 feat: catch ExpiredSignatureError in identity_service
  identity_service/utils/jwt_controller.py
Labels: bug

#92 fix: move access token to header in gateway
  gateway/app/middleware/auth.py
  gateway/app/routers/events.py
  gateway/app/routers/invites.py
  gateway/app/routers/notification.py
  gateway/app/routers/users.py
  identity_service/main.py
Labels: enhancement

#93 fix: typo in route path in gateway
  gateway/app/routers/events.py
Labels: bug

#100 feat: allow CORS in gateway
  gateway/app/main.py
  gateway/poetry.lock
  gateway/pyproject.toml
Labels: enhancement

#101 fix: typo in get_event route and add default value to CreateEventRequest
  gateway/app/routers/events.py
Labels: bug

#96 feat: add main readme
  README.md
Labels: documentation

#85 Fix: Move all queries to transaction in create notification in repository impl
  notification_service/repository/notification_repository_impl.py
Labels: enhancement

#83 Fix: Add return objects for requests and correct return types in proto for invite service
  invite_service/main.py
  invite_service/prisma/schema.prisma
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  shared/proto/invite_service/invite_service.proto
Labels: enhancement

#95 feat: add readme to gateway
  gateway/README.md
Labels: documentation

#94 Feat: Create README for identity service
  identity_service/README.md
Labels: documentation

#104 Fix: Get repeating events
  event_service/constants.py
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/src/models/event.py
Labels: bug

#108 Fix: Queries syntax
  event_service/repository/event_repository_impl.py
Labels: bug

#90 Feat: Create README.md for notification service
  notification_service/README.md
Labels: documentation

#87 Feat: Create readme for event service
  event_service/README.md
  shared/proto/event_service/event_service.proto
Labels: documentation

#106 Fix: Corrected README for identity service
  identity_service/README.md
Labels: documentation

#102 feat: return empty array instead of error
  event_service/repository/event_repository_impl.py
  gateway/app/routers/events.py
  gateway/app/routers/invites.py
  gateway/app/routers/notification.py
  identity_service/repository/mock_user_repository.py
  identity_service/repository/user_repository_impl.py
  identity_service/repository/user_repository_interface.py
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
  notification_service/repository/notification_repository_interface.py
Labels: enhancement

#107 Fix: Correct time interval in mock
  event_service/repository/mock_event_repository.py
  event_service/src/models/event.py
Labels: bug

#105 Feat: Create new request methods for notification service
  notification_service/constants.py
  notification_service/errors/wrong_inerval_error.py
  notification_service/poetry.lock
  notification_service/prisma/schema.prisma
  notification_service/pyproject.toml
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
  notification_service/repository/notification_repository_interface.py
  notification_service/src/models/notification.py
  notification_service/src/notification_service_impl.py
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#91 Feat: Create README.md for invite service
  invite_service/README.md
Labels: documentation

#113 Fix: notification and event routes in gateway
  event_service.Dockerfile
  event_service/src/models/event.py
  gateway.Dockerfile
  gateway/app/errors/unauthenticated_error.py
  gateway/app/middleware/auth.py
  gateway/app/middleware/interceptor.py
  gateway/app/models/Interval.py
  gateway/app/models/event.py
  gateway/app/models/notification.py
  gateway/app/routers/__init__.py
  gateway/app/routers/events.py
  gateway/app/routers/notifications.py
  gateway/poetry.lock
  gateway/pyproject.toml
  notification_service.Dockerfile
  notification_service/src/models/notification.py
  shared/proto/event_service/event_service.proto
  shared/proto/interval/interval.proto
  shared/proto/notification_service/notification_service.proto
Labels: bug

#111 Fix: Changed structure of get notifications by ids requests
  notification_service/src/notification_service_impl.py
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#114 feat: map prisma to already existing table fields
  .gitignore
  event_service.Dockerfile
  event_service/prisma/schema.prisma
  identity_service.Dockerfile
  identity_service/prisma/schema.prisma
  invite_service.Dockerfile
  invite_service/prisma/schema.prisma
  notification_service.Dockerfile
  notification_service/prisma/schema.prisma
Labels: enhancement

#110 Fix: Generating of SQL queries
  event_service/repository/event_repository_impl.py
  event_service/repository/mock_event_repository.py
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
Labels: bug

#112 Fix: Store time in UTC in invite service
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/models/invite.py
Labels: bug

#116 Fix: File structure in event service
  .dockerignore
  .gitignore
  event_service.Dockerfile
  event_service/README.md
  event_service/poetry.lock
  event_service/src/__init__.py
  event_service/src/constants/__init__.py
  event_service/src/constants/constants.py
  event_service/src/event_service_impl.py
  event_service/src/main.py
  event_service/src/models/__init__.py
  event_service/src/models/event.py
  event_service/src/repository/__init__.py
  event_service/src/repository/event_repository_impl.py
  event_service/src/repository/event_repository_interface.py
  event_service/src/repository/mock_event_repository.py
  event_service/src/utilities/__init__.py
  event_service/src/utilities/ai_client.py
  event_service/src/utilities/custom_interceptor.py
  pyproject.toml
  shared/db_package/db/postgres_client.py
  shared/db_package/poetry.lock
  shared/db_package/pyproject.toml
  tox.ini
Labels: enhancement

#109 Fix: store datetime in utc in identity_service
  identity_service/repository/mock_user_repository.py
  identity_service/repository/user_repository_impl.py
  identity_service/src/models/user.py
Labels: bug

#118 Fix: Invite service file structure
  .dockerignore
  .gitignore
  invite_service.Dockerfile
  invite_service/README.md
  invite_service/poetry.lock
  invite_service/src/interceptor/__init__.py
  invite_service/src/interceptor/custom_interceptor.py
  invite_service/src/invite_service_impl.py
  invite_service/src/main.py
  invite_service/src/models/__init__.py
  invite_service/src/models/invite.py
  invite_service/src/repository/init.py
  invite_service/src/repository/invite_repository_impl.py
  invite_service/src/repository/invite_repository_interface.py
  invite_service/src/repository/mock_invite_repository.py
  pyproject.toml
  tox.ini
Labels: enhancement

#119 Fix: identity service file structure
  .dockerignore
  .gitignore
  identity_service.Dockerfile
  identity_service/README.md
  identity_service/poetry.lock
  identity_service/src/__init__.py
  identity_service/src/identity_service_impl.py
  identity_service/src/main.py
  identity_service/src/models/__init__.py
  identity_service/src/models/user.py
  identity_service/src/repository/__init__.py
  identity_service/src/repository/mock_token_repository.py
  identity_service/src/repository/mock_user_repository.py
  identity_service/src/repository/token_repository_impl.py
  identity_service/src/repository/token_repository_interface.py
  identity_service/src/repository/user_repository_impl.py
  identity_service/src/repository/user_repository_interface.py
  identity_service/src/utilities/__init__.py
  identity_service/src/utilities/custom_interceptor.py
  identity_service/src/utilities/encoder.py
  identity_service/src/utilities/jwt_controller.py
Labels: enhancement

#117 Fix: Notification service file structure
  .dockerignore
  .gitignore
  event_service.Dockerfile
  event_service/README.md
  event_service/src/main.py
  event_service/src/repository/__init__.py
  event_service/src/utilities/__init__.py
  notification_service.Dockerfile
  notification_service/README.md
  notification_service/poetry.lock
  notification_service/src/__init__.py
  notification_service/src/constants/__init__.py
  notification_service/src/constants/constants.py
  notification_service/src/interceptor/__init__.py
  notification_service/src/interceptor/custom_interceptor.py
  notification_service/src/main.py
  notification_service/src/models/__init__.py
  notification_service/src/models/notification.py
  notification_service/src/notification_service_impl.py
  notification_service/src/repository/__init__.py
  notification_service/src/repository/mock_notification_repository.py
  notification_service/src/repository/notification_repository_impl.py
  notification_service/src/repository/notification_repository_interface.py
  pyproject.toml
  tox.ini
Labels: enhancement

#120 Feat/return notification in event route in gateway
  gateway/app/routers/events.py
  gateway/app/routers/invites.py
  gateway/app/routers/notifications.py
  gateway/app/utils/__init__.py
  gateway/app/utils/event_permission_checker.py
  gateway/app/utils/event_start_to_notification_start_converter.py
  gateway/app/utils/user_existence_checker.py
Labels: enhancement

#121 Fix: main and gateway readmes
  README.md
  deployments/gateway/gateway_service.yaml
  gateway/README.md
Labels: bug

#122 Feat: Add delay field for notifications
  notification_service/README.md
  notification_service/prisma/schema.prisma
  notification_service/src/constants/constants.py
  notification_service/src/models/notification.py
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#123 Fix: errors when getting invites and notification in get event in gateway
  gateway/app/routers/events.py
  gateway/app/utils/event_permission_checker.py
  invite_service/src/repository/mock_invite_repository.py
Labels: bug

#124 Fix: File structure in invite service
  invite_service/src/__init__.py
  invite_service/src/repository/__init__.py
Labels: bug

#125 Feat: add delay to notification in gateway
  gateway/app/models/notification.py
  gateway/app/routers/events.py
  gateway/app/routers/notifications.py
Labels: enhancement

#126 fix: deployment
  deployments/gateway/gateway_deployment.yaml
  deployments/gateway/gateway_service.yaml
  gateway/README.md
  gateway/app/grpc_client/grpc_client.py
Labels: bug

#129 Fix: Remove extra fields in proto for notification service
  notification_service/src/constants/constants.py
  shared/proto/notification_service/notification_service.proto
Labels: bug, documentation

#128 Fix: create notification with event returns notification with wrong id
  gateway/app/routers/events.py
  gateway/app/routers/notifications.py
Labels: bug

#127 Fix: AI client
  event_service/src/constants/constants.py
  event_service/src/repository/event_repository_impl.py
  event_service/src/utilities/ai_client.py
  gateway/app/middleware/interceptor.py
Labels: bug, documentation

#72 Feat: add rate limiter to gateway
  .gitignore
  .pre-commit-config.yaml
  README.md
  deployments/redis/redis-service.yaml
  deployments/redis/redis_deployment.yaml
  gateway/app/main.py
  gateway/app/middleware/interceptor.py
  gateway/app/middleware/rate_limiter.py
  gateway/poetry.lock
  gateway/pyproject.toml
  shared/errors_package/errors/__init__.py
  shared/errors_package/errors/rate_limit_error.py
Labels: enhancement

#131 fix: users cant log out
  gateway/app/routers/users.py
Labels: bug

#130 fix: update notifications when updating event
  gateway/app/main.py
  gateway/app/models/Interval.py
  gateway/app/routers/events.py
Labels: bug

#132 Fix: make password field optional in update user
  gateway/app/middleware/interceptor.py
  gateway/app/models/user.py
  gateway/app/routers/users.py
  gateway/app/validators/__init__.py
  gateway/app/validators/str_validators.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
  shared/proto/identity_service/update_user.proto
Labels: bug

#133 feat: missing env variable in gateway_deployment.yaml
  deployments/gateway/gateway_deployment.yaml
Labels: bug

#134 Fix: add missing cors to too many requests
  README.md
  deployments/gateway/gateway_deployment.yaml
  gateway/README.md
  gateway/app/main.py
  gateway/app/middleware/interceptor.py
Labels: bug

#135 Fix: typo in docstring in notification service
  event_service/src/constants/constants.py
  event_service/src/repository/event_repository_impl.py
  notification_service/src/constants/constants.py
  notification_service/src/repository/notification_repository_impl.py
Labels: bug, documentation

#136 Fix: unhandled error in gateway
  gateway/app/models/event.py
  gateway/app/models/invite.py
  gateway/app/models/notification.py
  gateway/app/models/user.py
  gateway/app/routers/events.py
  identity_service/README.md
Labels: bug
