Repository UnspokenTeam/Calendar, pull requests merged in 2024-04, with the labels that each got.

#30 Feat: added pagination
  event_service/prisma/schema.prisma
  event_service/proto/event_service.proto
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/src/models/event.py
Labels: enhancement

#31 feat: add pagination
  identity_service/proto/get_user.proto
  identity_service/repository/mock_user_repository.py
  identity_service/repository/user_repository_impl.py
  identity_service/repository/user_repository_interface.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
Labels: enhancement

#34 Feat/add GitHub action for building images
  .github/workflows/build_event_service.yaml
  .github/workflows/build_gateway.yaml
  .github/workflows/build_identity_service.yaml
  .github/workflows/build_invite_service.yaml
  .github/workflows/build_notification_service.yaml
Labels: enhancement

#36 Feat: add grpc interceptors for event service
  identity_service/db/postgres_client.py
  identity_service/errors/invalid_token_error.py
  identity_service/errors/permission_denied.py
  identity_service/main.py
  identity_service/poetry.lock
  identity_service/proto/auth.proto
  identity_service/proto/get_access_token.proto
  identity_service/proto/get_user.proto
  identity_service/proto/identity_service.proto
  identity_service/pyproject.toml
  identity_service/repository/user_repository_impl.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
  identity_service/utils/custom_interceptor.py
  identity_service/utils/jwt_controller.py
  pyproject.toml
Labels: enhancement

#39 fix: buids not triggering
  .github/workflows/build_event_service.yaml
  .github/workflows/build_gateway.yaml
  .github/workflows/build_identity_service.yaml
  .github/workflows/build_invite_service.yaml
  .github/workflows/build_notification_service.yaml
  identity_service/proto/get_access_token.proto
  identity_service/src/identity_service_impl.py
Labels: bug

#38 Feat: Add interceptor
  event_service/db/postgres_client.py
  event_service/errors/permission_denied.py
  event_service/main.py
  event_service/poetry.lock
  event_service/prisma/schema.prisma
  event_service/proto/event_service.proto
  event_service/pyproject.toml
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/utils/custom_interceptor.py
Labels: enhancement

#41 feat: add protoleteriat and delete 2to3 in identiti_service
  .gitignore
  identity_service/.dockerignore
  identity_service/Dockerfile
  identity_service/poetry.lock
  identity_service/pyproject.toml
  identity_service/repository/user_repository_impl.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
  identity_service/utils/custom_interceptor.py
Labels: enhancement

#44 fix: change dockerfile locations
  .github/workflows/build_event_service.yaml
  .github/workflows/build_gateway.yaml
  .github/workflows/build_identity_service.yaml
  .github/workflows/build_invite_service.yaml
  .github/workflows/build_notification_service.yaml
Labels: bug

#45 Fix:change dockerfile to file inside github actions
  .github/workflows/build_event_service.yaml
  .github/workflows/build_gateway.yaml
  .github/workflows/build_identity_service.yaml
  .github/workflows/build_invite_service.yaml
  .github/workflows/build_notification_service.yaml
Labels: bug

#42 Feat: Integrated AI Client
  event_service/constants.py
  event_service/db/postgres_client.py
  event_service/errors/ai_response_error.py
  event_service/errors/permission_denied_error.py
  event_service/poetry.lock
  event_service/pyproject.toml
  event_service/repository/event_repository_impl.py
  event_service/repository/event_repository_interface.py
  event_service/repository/mock_event_repository.py
  event_service/src/event_service_impl.py
  event_service/src/models/event.py
  event_service/utils/ai_client.py
  event_service/utils/custom_interceptor.py
  identity_service/db/postgres_client.py
  identity_service/repository/mock_token_repository.py
  identity_service/repository/mock_user_repository.py
  identity_service/repository/token_repository_impl.py
  identity_service/repository/token_repository_interface.py
  identity_service/repository/user_repository_impl.py
  identity_service/repository/user_repository_interface.py
  identity_service/src/identity_service_impl.py
  identity_service/src/models/user.py
  identity_service/utils/encoder.py
  identity_service/utils/jwt_controller.py
  invite_service/db/postgres_client.py
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  invite_service/src/models/invite.py
  pyproject.toml
  shared/proto/event_service/event_service.proto
  tox.ini
Labels: enhancement

#48 Feat: setup gateway
  .gitignore
  .pre-commit-config.yaml
  gateway/.dockerignore
  gateway/Dockerfile
  gateway/app/__init__.py
  gateway/app/grpc_client/__init__.py
  gateway/app/grpc_client/grpc_client.py
  gateway/app/main.py
  gateway/app/params/__init__.py
  gateway/app/params/grpc_client_params.py
  gateway/app/routers/__init__.py
  gateway/app/routers/events.py
  gateway/poetry.lock
  gateway/pyproject.toml
  invite_service/main.py
  pyproject.toml
  tox.ini
Labels: enhancement

#50 Fix: fix project files
  pyproject.toml
  tox.ini
Labels: bug

#51 Fix: fix event service
  event_service/main.py
  event_service/src/event_service_impl.py
  event_service/utils/ai_client.py
Labels: bug

#52 Feat: add user routes to gateway
  .dockerignore
  .github/workflows/build_event_service.yaml
  .github/workflows/build_gateway.yaml
  .github/workflows/build_identity_service.yaml
  .github/workflows/build_invite_service.yaml
  .github/workflows/build_notification_service.yaml
  .gitignore
  event_service/.dockerignore
  event_service/src/event_service_impl.py
  gateway.Dockerfile
  gateway/.dockerignore
  gateway/Dockerfile
  gateway/app/constants/__init__.py
  gateway/app/errors/__init__.py
  gateway/app/errors/permission_denied.py
  gateway/app/errors/unauthorized.py
  gateway/app/grpc_client/__init__.py
  gateway/app/grpc_client/grpc_client.py
  gateway/app/main.py
  gateway/app/middleware/__init__.py
  gateway/app/middleware/auth.py
  gateway/app/models/__init__.py
  gateway/app/models/user.py
  gateway/app/params/__init__.py
  gateway/app/params/grpc_client_params.py
  gateway/app/routers/__init__.py
  gateway/app/routers/events.py
  gateway/app/routers/users.py
  gateway/app/validators/__init__.py
  gateway/app/validators/str_validators.py
  gateway/poetry.lock
  gateway/pyproject.toml
  identity_service/.dockerignore
  identity_service/src/identity_service_impl.py
  invite_service/.dockerignore
  invite_service/src/invite_service_impl.py
  notification_service/.dockerignore
  notification_service/src/notification_service_impl.py
  shared/proto/event_service/event_service.proto
  shared/proto/invite_service/invite_service.proto
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#54 Feat/create testing environment
  event_service.Dockerfile
  event_service/main.py
  event_service/src/event_service_impl.py
  identity_service.Dockerfile
  identity_service/main.py
  identity_service/utils/jwt_controller.py
  invite_service.Dockerfile
  invite_service/main.py
  notification_service.Dockerfile
  notification_service/main.py
Labels: enhancement

#53 fix: fix TypeError for returning type in get_user_by_id
  identity_service/src/identity_service_impl.py
Labels: bug

#56 Fix: fix small things in event and notification services
  notification_service/errors/unique_error.py
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
  notification_service/repository/notification_repository_interface.py
  notification_service/src/models/notification.py
  notification_service/src/notification_service_impl.py
  notification_service/utils/custom_interceptor.py
  shared/proto/event_service/event_service.proto
  shared/proto/notification_service/notification_service.proto
Labels: bug

#61 Feat: add variations of delete action for invite service
  invite_service/errors/unique_error.py
  invite_service/prisma/schema.prisma
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  invite_service/src/models/invite.py
  shared/proto/invite_service/invite_service.proto
  shared/proto/user/user.proto
Labels: bug, enhancement

#59 Fix: Pagination in mock notification repository
  notification_service/repository/mock_notification_repository.py
Labels: bug

#65 feat: return all users if items_per_page is equal to -1
  identity_service/repository/mock_user_repository.py
  identity_service/repository/user_repository_impl.py
Labels: enhancement

#64 fix: delete pop in mock repository when deleting user in identity service
  identity_service/repository/mock_user_repository.py
Labels: bug

#63 fix: use oneof instead of optional fields
  identity_service/src/models/user.py
  shared/proto/identity_service/update_user.proto
Labels: bug

#66 feat: add getter for invites by event_id
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  shared/proto/invite_service/invite_service.proto
Labels: enhancement

#69 fix: add getter by email to identity service
  identity_service/repository/user_repository_impl.py
  identity_service/src/identity_service_impl.py
  shared/proto/identity_service/get_user.proto
  shared/proto/identity_service/identity_service.proto
Labels: enhancement

#68 feat: add interceptor middleware for gateway
  gateway/app/errors/__init__.py
  gateway/app/errors/unauthorized.py
  gateway/app/main.py
  gateway/app/middleware/__init__.py
  gateway/app/middleware/auth.py
  gateway/app/middleware/interceptor.py
  gateway/app/params/grpc_client_params.py
Labels: enhancement

#70 Feat: Added get_notification_by_event_and_author_ids
  notification_service/repository/mock_notification_repository.py
  notification_service/repository/notification_repository_impl.py
  notification_service/repository/notification_repository_interface.py
  notification_service/src/notification_service_impl.py
  shared/proto/notification_service/notification_service.proto
Labels: enhancement

#67 Feat: interceptor for invite service
  invite_service/main.py
  invite_service/poetry.lock
  invite_service/pyproject.toml
  invite_service/repository/invite_repository_impl.py
  invite_service/repository/invite_repository_interface.py
  invite_service/repository/mock_invite_repository.py
  invite_service/src/invite_service_impl.py
  invite_service/utils/custom_interceptor.py
  shared/proto/invite_service/invite_service.proto
Labels: enhancement
